### ISSUE TITLE
still getting console side message in latest builds

### ISSUE THREAD

**Issue by ghost** [cnaude/PurpleIRC-spigot#1]
using latest spigot build of purple and spigot i still get the messages going to console instead. would you like me to paste my configs?

**Comment by cnaude** [comment]
What commands are sending output to the console? Right now Spigot doesn't support custom custom CommandSenders for vanilla commands. I might be able to come up with a workaround for specific commands.

**Comment by ghost** [comment]
Well it would be a lot of einfo triggers and tons of custom commands so maybe look at my bot and let me know? I am using an older version currently.

http://pastebin.com/y8NqX0hE

**Comment by cnaude** [comment]
The very latest version of PurpleIRC will detect custom commands and dispatch them correctly to allow for output returned to IRC. The only issue is vanilla commands.

**Comment by ghost** [comment]
odd because it was the einfo command that was going to the console, coudl that have something to do with spigot-essentials

**Comment by cnaude** [comment]
The einfo command is what i tested in the latest version :)

**Comment by ghost** [comment]
okay ill try again soon and let you know.

**Comment by cnaude** [comment]
Closing very old tickets. Let me know if this is still an issue.
