### ISSUE TITLE
Suggestion: Multiple raw messages on join

### ISSUE THREAD

**Issue by craze** [cnaude/PurpleIRC-spigot#15]
On some occasions more than one message needs to be sent to the IRC server on join.
Is there a known workaround for this, or would it be feasible to include this in a future update?

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/189/
You can add the option raw-message-list to your bot.yml.

**Comment by craze** [comment]
The new build appears to do what I requested.
Thank you! d-(",)z
