### ISSUE TITLE
IRC to Minecraft chat not showing between build 10 and 12

### ISSUE THREAD

**Issue by RoyCurtis** [cnaude/PurpleIRC-spigot#2]
Chat on IRC was no longer showing up in-world after upgrading from [build 10](http://h.cnaude.org:8081/job/PurpleIRC-spigot/10/) to [build 12](http://h.cnaude.org:8081/job/PurpleIRC-spigot/12/). I have a feeling [this commit](https://github.com/cnaude/PurpleIRC-spigot/commit/6b81d2094ffbb96d10a7756005333e670c977082) is the culprit. Downgrading to build 10 resolved the issue.
# Details
- `This server is running CraftBukkit version git-Spigot-899f5ee-1092acb (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)`
- PurpleIRC configuration: https://gist.github.com/RoyCurtis/d98f845fe64e5edfcb99
- Bot configuration: https://gist.github.com/RoyCurtis/5f7360d07eb1d53ed8d7
- Plugin list: http://i.imgur.com/70XMMGa.png
- Build 10 test: http://i.imgur.com/nhsu57X.png
- Build 12 test: http://i.imgur.com/cR96ipH.png

**Comment by cnaude** [comment]
Please test the build again but this time with debug mode enabled. You can do that with "/irc debug t". Send a few test messages and then send me the console log output.

**Comment by RoyCurtis** [comment]
Understood; forgive me as I will not be able to get back to you with the results until tonight

**Comment by cnaude** [comment]
Where did you download that version on zPermissions? 
Edit: Nevermind i found it :)

**Comment by cnaude** [comment]
Okay I was able to replicate the problem. I think it's an issue with zPermissions and Vault. Now to fix...

**Comment by cnaude** [comment]
Fixed in build 13.
http://h.cnaude.org:8081/job/PurpleIRC-spigot/13/

**Comment by RoyCurtis** [comment]
Can now confirm that the latest build is working for me also. Thank you very much!
