### ISSUE TITLE
Color code is no longer working.

### ISSUE THREAD

**Issue by jimchen5209** [cnaude/PurpleIRC-spigot#20]
After I update to build 223,any color codes is no longer working,incuding the message in the config file,I want the color code support back.

Before(215):
![image](https://cloud.githubusercontent.com/assets/10269287/16572255/4193026a-4299-11e6-80d6-cc94bb38e903.png)

After(223):
![image](https://cloud.githubusercontent.com/assets/10269287/16572267/6f03c8ce-4299-11e6-89b5-8ce753c412eb.png)

Spigot version: 1.9.4

**Comment by cnaude** [comment]
I'm working on a fix. For now set "strip-game-colors-from-irc: false" in your config.yml.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/224/

**Comment by jimchen5209** [comment]
Thanks,It works properly now.

2016-07-05 13:28 GMT+08:00 Chris notifications@github.com:
