### ISSUE TITLE
onMessage: String index out of range: -1

### ISSUE THREAD

**Issue by k-jiang** [cnaude/PurpleIRC-spigot#21]
PurpleIRC-1.0.224
Spigot 1.10.2 build 904
Using IRC server on Linux

> [PurpleIRC] onMessage: String index out of range: -1
> java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>         at java.lang.String.substring(String.java:1931)
>         at com.cnaude.purpleirc.IRCMessageHandler.processMessage(IRCMessageHandler.java:79)
>         at com.cnaude.purpleirc.IRCListeners.MessageListener.onMessage(MessageListener.java:68)
>         at com.cnaude.purpleirc.ext.org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:66)
>         at com.cnaude.purpleirc.ext.org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:119)
>         at com.cnaude.purpleirc.ext.org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:114)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

**Comment by cnaude** [comment]
What do you have command-prefix: set to in your bot yml file?

**Comment by cnaude** [comment]
Should be fixed in latest Jenkins build.

**Comment by k-jiang** [comment]
bot.yml

> command-prefix: .

I never ever touch it since installed years ago. Is this a default value?

**Comment by k-jiang** [comment]
Tested on build 225, it's seems fine right now. Thank you!
