### ISSUE TITLE
[Proposal] Jenkins `PurpleIRC.jar` artifact

### ISSUE THREAD

**Issue by RoyCurtis** [cnaude/PurpleIRC-spigot#23]
May I please ask that the PurpleIRC Jenkins generates an artifact simply called [`PurpleIRC.jar`](http://h.cnaude.org:8081/jenkins/job/PurpleIRC-Spigot/lastSuccessfulBuild/artifact/target/PurpleIRC.jar), along-side the versioned one? (e.g. `PurpleIRC-1.0-244.jar`)

# Rationale

For our server, [I use a shell script to update our plugins from various sources](https://gist.github.com/RoyCurtis/22c80f0b5bb4b84f446d). Some of these sources are Jenkins repositories, like PurpleIRC's.

For Jenkins, we rely on the `jenkins/job/PurpleIRC-Spigot/lastSuccessfulBuild/` endpoint to always get the latest build. For example:

* https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/artifact/paperclip.jar
* http://h.cnaude.org:8081/job/VanishNoPacket/lastSuccessfulBuild/artifact/target/VanishNoPacket.jar

However, PurpleIRC's Jenkins only has one artifact, and it has the build number on it. This means that the script breaks when a new version of PurpleIRC is built.

# Notes

* This script is not run abusively (e.g. every 5 minutes). On our 1.11 BETA, it's run manually and at 00:00 EST. On our live server, it's run manually at least once a week.
* I could instead use a [build's perma-link](http://h.cnaude.org:8081/jenkins/job/PurpleIRC-Spigot/244/artifact/target/PurpleIRC-1.0-244.jar), but I would prefer to be on the bleeding-edge at all times and avoid updating `update.sh` manually
* Thank you for continuing to update PurpleIRC into 1.11!

**Comment by cnaude** [comment]
See https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/245/

**Comment by RoyCurtis** [comment]
Thank you very much! A small change goes a long way :)
