### ISSUE TITLE
Discord bridge chat send to irc

### ISSUE THREAD

**Issue by 123DMWM** [cnaude/PurpleIRC-spigot#26]
- irc-discord-chat enables irc messages to be sent to the discord channel, but not the other way around.

**Comment by popcorn9499** [comment]
Im having the exact same problem. Im unsure whats causing this

**Comment by cnaude** [comment]
Have you tried to add "discord-chat" to the enabled-messages section of the bot yml? Can I see the debug log if it's not working correctly?

**Comment by popcorn9499** [comment]
it works on discord srv v11 but not on v12.3 will update with debug log shortly

**Comment by popcorn9499** [comment]
This  is the [log file](http://pastebin.com/CTgxwQCK) That should give you everything you need to know. Tell me if you would like the log without the other  plugins to make it easier to read. Hope  this helps

**Comment by cnaude** [comment]
The debug log helps a lot. According to the log it can't find the discord channel by name. Would you mind trying the latest dev build? It has some additional debugging that may help.

**Comment by popcorn9499** [comment]
[additional logs](http://pastebin.com/h9neJ17J) This should help.

**Comment by popcorn9499** [comment]
testing on version 11 of discord srv. the purple irc hook seemed to be pulling chat from all the channels in discord as well. Im unsure if these issues are related or not.

**Comment by cnaude** [comment]
I was able to replicate the issue on my test server. I'll let you know when I have a fix.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/262/

**Comment by popcorn9499** [comment]
Discordsrv Push's messages to the IRC from purple irc now but still pulls from all the channels it has read access to from discordsrv

**Comment by cnaude** [comment]
@popcorn9499 what message types are in your bot's enabled-messages section?

**Comment by popcorn9499** [comment]
This is what I've got enabled in the bots message section http://pastebin.com/Fy8wWc1n

**Comment by cnaude** [comment]
@popcorn9499 discord-chat is a catch-all message type. If you only want messages from a specific channel use discord-CHANNEL-chat and replace CHANNEL with the channel in discord.
