### ISSUE TITLE
IPv6 connection

### ISSUE THREAD

**Issue by R3duct1on** [cnaude/PurpleIRC-spigot#27]
Seems like my PurpleIRC can't connect to a Server behind a IPv6 Adresse.
I've tried it to my Server with a direct connection to a IPv6 adress and then over a domain with AAAA Record. Both attempts failed. Then I tried some other IPv6 IRC Servers, coundt connect to anyone.
IPv4 works fine.

Is this just a configuration failure or does the Plugin need a "protocol" update for this?

**Comment by Robby-** [comment]
Very likely a configuration failure, perhaps even at the operating system level.
PurpleIRC's IPv6 connectivity works just fine for me.
