### ISSUE TITLE
discordsrv 13.3 hook problems

### ISSUE THREAD

**Issue by popcorn9499** [cnaude/PurpleIRC-spigot#30]
It looks like the hooks for discordsrv that you used dont work in the newer version of purple irc. it looks like a update is in order. im running purpleirc build 279 and discordsrv 13.3

im not sure what else was needed ill check the logs shortly

**Comment by cnaude** [comment]
Please try build 280.
https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/280/

**Comment by popcorn9499** [comment]
sorry i havent responded. got abit busy anyways. i tried the lastest build and it didnt work.
I tested all the discordsrv 13.x versions and purple irc build 283 and 280. both of which didnt hook in correctly. Like irc didnt go to discord and discord didnt go to irc

**Comment by cnaude** [comment]
I've been testing the new API in version 13.x and believe the issue is on the DiscordSRV side.

**Comment by cnaude** [comment]
I downloaded the DiscordSRV code so that i can add some additional debugging and figure out exactly where the messages are getting dropped.

**Comment by popcorn9499** [comment]
ok thanks. the old discordsrv version stopped working. I never really understood why and this is why i got pushed to this version. kinda sucky that something changed to make this break. isnt it?

**Comment by cnaude** [comment]
I've sent a pull request to fix one of the new API bugs. This will fix the issue of the messages from Discord not being received by PurpleIRC.
https://github.com/Scarsz/DiscordSRV/pull/168

**Comment by cnaude** [comment]
Go ahead and try the latest dev builds. 
http://scarsz.tech:8080/job/DiscordSRV/
https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/285/
