### ISSUE TITLE
Deprecated Event Warning

### ISSUE THREAD

**Issue by PIE-yt** [cnaude/PurpleIRC-spigot#32]
`WARN [PurpleIRC] "PurpleIRC v1.0-285" has registered a listener for org.bukkit.event.player.PlayerAchievementAwardedEvent on method "public void com.cnaude.purpleirc.GameListeners.GamePlayerPlayerAchievementAwardedListener.onPlayerAchievementAwardedEvent(org.bukkit.event.player.PlayerAchievementAwardedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [cnaude].`

Hi
I'm receiving the above warning at startup with the latest Spigot (git-Spigot-d276ab1-d219213). Just thought I'd let you know as it suggests.

Thanks for your time.

**Comment by cnaude** [comment]
Yeah that will break when 1.12 is released. Not a big deal right now since there is nothing to replace it in 1.11.2.

**Comment by lwl12** [comment]
```[PurpleIRC] "PurpleIRC v1.0-324" has registered a listener for org.bukkit.event.player.PlayerAchievementAwardedEvent on method "public void com.cnaude.purpleirc.GameListeners.GamePlayerPlayerAchievementAwardedListener.onPlayerAchievementAwardedEvent(org.bukkit.event.player.PlayerAchievementAwardedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [cnaude].```

I see the same error when using Paperspigot 1.13.2 =_=||

**Comment by cnaude** [comment]
Try https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/327/

**Comment by lwl12** [comment]
Nice work! There is no annoying WARN now, thanks~
