### ISSUE TITLE
IRC to console not working, and .gamemode sends private message. 

### ISSUE THREAD

**Issue by jowanw** [cnaude/PurpleIRC-spigot#4]
Hello me again.

My IRC to console isnt working. im running version 61 of PurpleIRC and This server is running CraftBukkit version git-Spigot-c136710-350cb99 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

In config: broadcast-chat-to-console: true

Debug: http://pastebin.com/0seJWqU2

And also when using .gamemode it sends the output in a pm on IRC.

Debug: http://pastebin.com/KDT8BjEk

Bot config: http://pastebin.com/QykTvwMC

**Comment by cnaude** [comment]
Please try build 62 and then send me the debug output. 

The private response in the gamemode command is a result of "private: true". Just change that to false.

**Comment by jowanw** [comment]
http://pastebin.com/AzPVihL6

**Comment by cnaude** [comment]
That's odd. The debug report shows the chat being sent to the console. As a work around you can add irc-console-chat to the enabled-messages section of the bot yml.

**Comment by cnaude** [comment]
Closing very old tickets. Let me know if this is still an issue.
