### ISSUE TITLE
Bot tries to join channels before it's finished identifying 

### ISSUE THREAD

**Issue by derram** [cnaude/PurpleIRC-spigot#40]
> [16:52:14 INFO]: [PurpleIRC] -NickServ-nick, type /msg NickServ IDENTIFY password. Otherwise,
> [16:52:14 INFO]: [PurpleIRC] -NickServ-This nickname is registered and protected. If it is your
> [16:52:14 INFO]: [PurpleIRC] -NickServ-please choose a different nick.
> [16:52:14 ERROR]: [PurpleIRC] :magnet.rizon.net 477 afmc #AltFurry :You need to login to services to join or speak in that channel.
> [16:52:14 INFO]: [PurpleIRC] -NickServ-Password accepted - you are now recognized.

This prevents it from joining channels that are set to +R, registered nicks only, on start up.  It has no problem joining when a join command is sent after the server is finished loading.

**Comment by cnaude** [comment]
You should be able to set the channel-auto-join-delay option in the bot yml.

**Comment by derram** [comment]
Yep, setting that to 40 got the bot to join on start.

Thanks!
