### ISSUE TITLE
%SERVER% and %CHANNELPREFIX% are not available

### ISSUE THREAD

**Issue by RZzHh** [cnaude/PurpleIRC-spigot#41]
hi
In version 1.13.2, most macro tokens are unavailable
PurpleIRC-spigot #329
paperclip #530
![image](https://user-images.githubusercontent.com/47564241/53564332-90f85000-3b91-11e9-8594-781f1feaa55a.png)
![image](https://user-images.githubusercontent.com/47564241/53564357-a1a8c600-3b91-11e9-8549-65686f56d4d9.png)
![image](https://user-images.githubusercontent.com/47564241/53564414-cb61ed00-3b91-11e9-8618-ace10d16de7f.png)
![image](https://user-images.githubusercontent.com/47564241/53564449-e9c7e880-3b91-11e9-9501-2fb0272ebe3a.png)

**Comment by cnaude** [comment]
Can I see what the console.log output looks like with PurpleIRC set to Debug mode? Startup log would be helpful too.
