### ISSUE TITLE
Ignore console channel in Discord

### ISSUE THREAD

**Issue by kolya5544** [cnaude/PurpleIRC-spigot#46]
We have a DiscordSRV channel for console commands, PurpleIRC hooks to it as well, but channel should be private, yet whenever I write anything to Discord console channel, it shows up in public IRC channel.
![Proofs](https://user-images.githubusercontent.com/20096248/75444575-ba021b00-5974-11ea-8844-08d5cde71dce.png)

**Comment by cnaude** [comment]
In your bot config remove discord-chat from the enable messages. Replace it with something like this: discord-[[CHANNEL_NAME]]-chat, where[[CHANNEL_NAME]] is the Discord channel name.

https://github.com/cnaude/PurpleIRC-spigot/blob/master/src/main/java/com/cnaude/purpleirc/PurpleBot.java#L1522
