### ISSUE TITLE
DiscordSRV messages get logged from every Discord text channel available to the bot

### ISSUE THREAD

**Issue by Vankka** [cnaude/PurpleIRC-spigot#47]
https://github.com/cnaude/PurpleIRC-spigot/blob/70d037e450006bc1d035bb6b7ca0af4974071437/src/main/java/com/cnaude/purpleirc/GameListeners/DiscordListener.java#L45

This method can be used to determine if the channel is actually being forwarded in-game (will return null otherwise) or the Discord Message Pre/Post Process event (if looking to know what messages DiscordSRV is sending)
https://github.com/DiscordSRV/DiscordSRV/blob/2502506a1ae526df46c101156389ed9eebc196e5/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L174

**Comment by md-5** [comment]
Fixed by changing `discord-chat` to `discord-channel-chat` in the bot yml

**Comment by Vankka** [comment]
Not sure if broadcasting literally every message the bot can see is a good idea still (even ones DiscordSRV isn't sending to players). But there's technically no issue here
