### ISSUE TITLE
Wait for nickserv identification before joining channels

### ISSUE THREAD

**Issue by AaronMcHale** [cnaude/PurpleIRC-spigot#6]
Our bot joins two channels, one is open to anyone, the other is restricted to only specific users (a staff channel).  The problem is the bot tries to join the restricted channel before identification with nickserv is completed, meaning it is unable to join the channel and I then have to manually tell it to join the channel.

A possible solution would be to add an config option to have the bot wait until it receives confirmation from nickserv that it has identified before auto-joining channels.

Thanks
Aaron

**Comment by cnaude** [comment]
As a workaround you can adjust the channel-auto-join-delay in your bot yml.

**Comment by AaronMcHale** [comment]
Hi, that worked thanks
