### ISSUE TITLE
Extra Information in Join/Quit Messages

### ISSUE THREAD

**Issue by Amiga60077** [cnaude/PurpleIRC-spigot#7]
Great mod, I would like to request a feature, the join/quit messages currently do not relay player information
Eg. [world] << Player Quit << - (%COUNT%/%MAX%): %PLAYERS%

I think it would be a good idea to allow this, like so:
Eg. [world] << Player Quit << - (3/200): Mick Jim Peter

This feature would be useful, as when players join/quit it would also show the currently active players in-game, Rather more handy than needing to type a command in irc to view the players list.

Thanks!

Additional: If servers have lots of Players Active (eg. Over 10), then the %PLAYERS% should be truncated to 10 etc to avoid overly long-line lengths

**Comment by cnaude** [comment]
http://h.cnaude.org:8081/job/PurpleIRC-spigot/134/
