### ISSUE TITLE
Bot names not updating completely.

### ISSUE THREAD

**Issue by GRRRillaNinja** [cnaude/PurpleIRC-spigot#8]
After changing my bot name from TheVoid to WNDR, I am still getting "Join: TheVoid" messages in IRC and server chat. However, the server chat is showing the new bot name "WNDR> TheVoid joined the channel".

Using latest version of PurpleIRC and Spigot 1.8.3

**Comment by cnaude** [comment]
Did you stop your server before making the change? I recommend stopping the server. Updating the bot yml file and then starting the server.

**Comment by GRRRillaNinja** [comment]
That worked thanks for the help Chris _thumbs up_
