### ISSUE TITLE
Possible to hook to SimpleTicketManager

### ISSUE THREAD

**Issue by ghost** [cnaude/PurpleIRC-spigot#9]
I am switching away from the now un-maintained ReportRTS ticket system for a better system. I am going to be using SimpleTicketManager shortly and wanted to know if it would be possible to hook to this system the same way ReportRTS is hooked, displaying and managing tickets from IRC is wonderful.

https://www.spigotmc.org/resources/simple-ticket-manager.4849/

**Comment by cnaude** [comment]
The developer of SimpleTicketManager will need to add events to his plugin. Once those events are available i can add the listeners to PurpleIRC just like ReportRTS.

**Comment by ghost** [comment]
Perhaps the developer @BearWoolley could weigh in on creating a hook in this thread?   https://github.com/BearWoolley/SimpleTicketManager

**Comment by ghost** [comment]
I am going to test out the latest purpleirc with the latest version of SimpleTicketManager as they have recently added support for purpleirc

**Comment by ghost** [comment]
I have this up and running, but not sure how to make it hook with STM, I do not see anything in the samplebot.yml on here, I did add the lines to the config.yml

Any suggestions?

**Comment by cnaude** [comment]
You should be ale to add the stm- message types to the enabled-messages section of the bot yml.

**Comment by cnaude** [comment]
See line 256 of https://github.com/cnaude/PurpleIRC-spigot/blob/master/src/main/resources/SampleBot.yml

**Comment by ghost** [comment]
I was able to add this howerver I got this message at startup:

```
[15:19:22] [Server thread/ERROR]: [PurpleIRC] Plugin PurpleIRC v1.0-195 has failed to register events for class com.cnaude.purpleirc.GameListeners.SimpleTicketManagerListener because uk/co/joshuawoolley/simpleticketmanager/events/SimpleTicketEvent does not exist.
```

**Comment by ghost** [comment]
Also it would seem that STM does not allow commands from the console, if I were to do `@report a new ticket message` it spits out:  `You must be a player to use this command`

**Comment by cnaude** [comment]
The "you must be a player" issue will need to be fixed on the STM side. The plugin needs to allow the commands to work from the console.

**Comment by cnaude** [comment]
It looks like the jar on spigot resource site does not have any of the event code that i submitted.

**Comment by ghost** [comment]
I noticed as well that the version on the spigot resource site breaks and looses tickets and has issues with MySQL. It does not look like the same version as listed on github. I'm likely going to have to go back to reportrts.

**Comment by BearWoolley** [comment]
I will look in to this when I get a chance.

**Comment by cnaude** [comment]
Closing very old tickets. Let me know if this is still an issue.
